# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
env:
  global:
    - _R_CHECK_DONTTEST_EXAMPLES_=FALSE

matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel